@startuml
actor User as user
package "GCS" as gcs {
    file text
}

card "Cloud Functions" as cf
database BQ as bq


user -up-> text : put
gcs -> cf : event
text -> cf : download
cf -> bq : load
@enduml